#==============================================#
# Map Ambience by RedSMURF: Configuration file #
#==============================================#

# To add a new ambience track, follow the example below
# [Ambience Name]
# AMBIENCE_MODEL                  = Path of ambience's model
# AMBIENCE_FLAGS                  = a - Model           b - Duration

# AMBIENCE_SPAWN_CHANCE           = Ambience's respawn probability (0.0 = never, 1.0 = always)
# AMBIENCE_SOUND                  = Path to the sound file for the ambience
# AMBIENCE_SOUND_DURATION         = Minimum - Maximum duration time for the ambience's sound
# AMBIENCE_SOUND_DELAY            = Minimum - Maximum delay time before the ambience's sound plays
# AMBIENCE_SOUND_VOL              = Volume of the ambience's sound
# AMBIENCE_SOUND_ATTN             = Attenuation of the ambience's sound
# AMBIENCE_SOUND_PITCH            = Pitch of the ambience's sound

# To make an ambience track available in the menu, you must define at least its name like this [Anything]
# ambience model and sound cannot be changed dynamically during gameplay

[Main Settings]
SETTING_DEFAULT_MODEL           = models/MapAmbience/discoball.mdl
SETTING_DEFAULT_FLAGS           = 0

SETTING_DEFAULT_FRAMERATE       = 1.0
SETTING_DEFAULT_SPAWN_CHANCE    = 1.0
SETTING_DEFAULT_SOUND           = MapAmbience/kylian-dictador.wav
SETTING_DEFAULT_SOUND_DURATION  = 12.0 15.0
SETTING_DEFAULT_SOUND_DELAY     = 2.0 5.0
SETTING_DEFAULT_SOUND_VOL       = 1.0
SETTING_DEFAULT_SOUND_ATTN      = 0.8
SETTING_DEFAULT_SOUND_PITCH     = 100

SETTING_AMBIENCE_LOAD           = 1             # Whether to load saved corpses data of the current map
SETTING_AMBIENCE_CHECK          = 10.0          # Maximum selection distance when checking nearby corpses
SETTING_OFFSET_BASE             = 120.0         # Default forward offset when previewing corpse placement
SETTING_OFFSET                  = 65.0 900.0    # Default minimum and maximum offset from the player to the corpse (MIN MAX)
SETTING_OFFSET_STEP             = 10.0          # Step size when scrolling to move corpse forward/backward
SETTING_GHOST_ALPHA             = 120           # Transparency level of the ghost preview model (0 - 255)

SETTING_SOUND_MENU_NAV          = buttons/blip1.wav
SETTING_SOUND_MENU_REMOVE       = buttons/button10.wav
SETTING_SOUND_MENU_ALERT        = buttons/bell1.wav

SETTING_COLOR_ACTIVE            = 0 255 0
SETTING_COLOR_INACTIVE          = 255 0 0

[Alien]
AMBIENCE_FLAGS                  = b
AMBIENCE_SOUND                  = ambience/alien_beacon.wav
AMBIENCE_SOUND                  = ambience/alien_blipper.wav
AMBIENCE_SOUND                  = ambience/alien_creeper.wav
AMBIENCE_SOUND                  = ambience/alien_squit.wav
AMBIENCE_SOUND                  = ambience/alienwind1.wav
AMBIENCE_SOUND                  = ambience/alienwind2.wav
AMBIENCE_SOUND_DURATION         = 15.0 22.0

[Wind]
AMBIENCE_FLAGS                  = b
AMBIENCE_SOUND                  = ambience/wind1.wav
AMBIENCE_SOUND                  = ambience/wind2.wav
AMBIENCE_SOUND_DURATION         = 15.0 22.0

[Warning 1]
AMBIENCE_SOUND                  = ambience/bigwarning.wav

[Warning 2]
AMBIENCE_SOUND                  = ambience/warn1.wav

[Warning 3]
AMBIENCE_SOUND                  = ambience/warn3.wav

[Burning]
AMBIENCE_SOUND                  = ambience/burning1.wav
AMBIENCE_SOUND                  = ambience/burning3.wav
AMBIENCE_SOUND_DURATION         = 15.0 22.0

[Computer]
AMBIENCE_FLAGS                  = b
AMBIENCE_SOUND                  = ambience/computalk1.wav
AMBIENCE_SOUND                  = ambience/computalk2.wav
AMBIENCE_SOUND_DURATION         = 15.0 22.0

[Cricket]
AMBIENCE_SOUND                  = ambience/cricket.wav

[Drips]
AMBIENCE_SOUND                  = ambience/drips.wav

[Flies]
AMBIENCE_SOUND                  = ambience/flies.wav

[Pumper]
AMBIENCE_SOUND                  = ambience/pumper.wav

[Rotor Machine]
AMBIENCE_SOUND                  = ambience/rotormachine.wav

[Scream Machine]
AMBIENCE_SOUND                  = ambience/screammachine.wav

[Siren]
AMBIENCE_SOUND                  = ambience/siren.wav

[Sparks]
AMBIENCE_SOUND                  = ambience/sparks.wav

[Squeeks]
AMBIENCE_SOUND                  = ambience/squeeks2.wav

[Zap Machine]
AMBIENCE_SOUND                  = ambience/zapmachine.wav

[Kylian Dictador]
AMBIENCE_SOUND                  = MapAmbience/kylian-dictador.wav